name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  BUILD_TYPE: Release
  PYTHONUNBUFFERED: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-11
          - macos-12
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022
    steps:
      - uses: actions/checkout@v3

      - name: Build (Unix)
        run: ./script/cibuild.py
        if: ${{ !startsWith(matrix.os, 'windows') }}

      - name: Build (Windows)
        run: py -3 .\script\run-in-vsenv.py py -3 .\script\cibuild.py
        if: ${{ startsWith(matrix.os, 'windows') }}
