name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  BUILD_TYPE: Release
  PYTHONUNBUFFERED: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: venv
          key: ${{ matrix.os }}-venv-${{ hashFiles('**/requirements.txt') }}

      - name: Build
        run: ./script/cibuild.py

  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
          - windows-2022
        arch:
          - x64
          - x86
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: venv
          key: ${{ matrix.os }}-${{ matrix.arch }}-venv-${{ hashFiles('**/requirements.txt') }}

      - name: Build
        run: py -3 .\script\run-in-vsenv.py --arch ${{ matrix.arch }} py -3 .\script\cibuild.py
