name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Ninja
        run: sudo apt-get install ninja-build

      - name: Configure
        run: cmake --preset default

      - name: Build
        run: cmake --build --preset default
